const categoryList = [
	'Food and beverage fairs',
	'Culinary festivals',
	'Beverage and cocktail exhibitions',
	'Gastronomic tasting events',
	'Local entrepreneurship and business',
	'Farmers markets',
	'Conferences and seminars on the food',
	'Networking events for industry',
	'Chef competitions and culinary',
	'Cultural events and local festivals',
	'Live music and art events',
	'Themed races and marathons',
	'Sports events and sponsorships',
	'Community celebrations and events',
	'Weddings and social gatherings',
	'Fundraising events',
	'Trade shows and exhibitions',
	'Product launch events',
	'Cooking workshops and classes',
	'Collaborative events with other businesses',
	'Others',
];
export default categoryList;
