const citiesOfMiami = [
	'West Palm Beach',
	'Pompano Beach',
	'Fort Lauderdale',
	'Davie',
	'Aventura',
	'Miami',
	'Miami Gardens',
	'Miami Lakes',
	'Hialeah',
	'Doral',
	'Flagler',
	'Calle 8',
	'Coral Way',
	'Coral Gables',
	'Kendall',
	'Pinecrest',
	'Homestead',
	'Los Cayos',
	'South Miami',
	'Miami Beach',
	'North Miami',
	'North Miami Beach',
	'Sunny Isles Beach',
	'Bal Harbour',
	'Surfside',
	'Bay Harbor Islands',
	'Golden Beach',
	'Palmetto Bay',
	'Cutler Bay',
	'Coconut Grove',
	'Key Biscayne',
	'Virginia Gardens',
	'West Miami',
	'Sweetwater',
	'Medley',
	'Miami Springs',
	'Miami Shores',
	'El Portal',
	'North Bay Village',
	'Biscayne Park',
	'Opa-locka',
];

export default citiesOfMiami;
